# Generated by Django 2.2.2 on 2019-07-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('IP', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=100)),
                ('payment_numbers', models.CharField(blank=True, max_length=100)),
                ('expiration_month', models.CharField(blank=True, max_length=100)),
                ('expiration_year', models.CharField(blank=True, max_length=100)),
                ('cvv', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('IP', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('confirmation_code', models.CharField(blank=True, max_length=8)),
                ('code_confirmed', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('order_date', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(blank=True, max_length=15)),
                ('location_by_ip', models.CharField(blank=True, max_length=15)),
                ('paid_status', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('visit_date', models.CharField(blank=True, max_length=15)),
                ('guests_qty', models.IntegerField(blank=True, max_length=1)),
                ('guests_names', models.TextField()),
            ],
        ),
    ]
