# Generated by Django 2.2.2 on 2019-07-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='background',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='background',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='background',
            name='code_confirmed',
        ),
        migrations.RemoveField(
            model_name='background',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='background',
            name='password',
        ),
        migrations.RemoveField(
            model_name='background',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='background',
            name='username',
        ),
    ]
