# Generated by Django 2.2.2 on 2019-07-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190725_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='expiration_month',
            new_name='expiration',
        ),
        migrations.RemoveField(
            model_name='background',
            name='expiration_year',
        ),
    ]
