# Generated by Django 2.2.2 on 2019-10-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_organization_organizationapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationapikey',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationAPIKey',
        ),
    ]
